# Generated by Django 5.1.2 on 2025-01-16 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90)),
                ('author', models.CharField(max_length=90)),
                ('genre', models.CharField(max_length=10)),
                ('publication_year', models.IntegerField()),
                ('available_copies', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='commune',
            name='ID_maghataa_id',
        ),
        migrations.RemoveField(
            model_name='village',
            name='ID_Commune',
        ),
        migrations.RemoveField(
            model_name='coordonneesgps',
            name='NumeroVillage',
        ),
        migrations.RemoveField(
            model_name='demographie',
            name='NumeroVillage',
        ),
        migrations.RemoveField(
            model_name='estimationressources',
            name='NumeroVillage',
        ),
        migrations.RemoveField(
            model_name='question',
            name='formilair',
        ),
        migrations.RemoveField(
            model_name='infrastructuresvillage',
            name='NumeroVillage',
        ),
        migrations.RemoveField(
            model_name='moughata',
            name='ID_wilaya',
        ),
        migrations.RemoveField(
            model_name='village',
            name='ID_Moughata',
        ),
        migrations.RemoveField(
            model_name='reponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='tel',
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default=' ', max_length=90, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterModelTable(
            name='users',
            table=None,
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(auto_now_add=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('penalty', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.users')),
            ],
        ),
        migrations.DeleteModel(
            name='ActivitesEconomiques',
        ),
        migrations.DeleteModel(
            name='Commune',
        ),
        migrations.DeleteModel(
            name='CoordonneesGPS',
        ),
        migrations.DeleteModel(
            name='Demographie',
        ),
        migrations.DeleteModel(
            name='EstimationRessources',
        ),
        migrations.DeleteModel(
            name='Formilair',
        ),
        migrations.DeleteModel(
            name='InfrastructuresVillage',
        ),
        migrations.DeleteModel(
            name='Wilaya',
        ),
        migrations.DeleteModel(
            name='Moughata',
        ),
        migrations.DeleteModel(
            name='Village',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Reponse',
        ),
    ]
