# Generated by Django 5.1.2 on 2025-01-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_borrow_is_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default='22000@gmail.com', max_length=40, unique=True),
        ),
        migrations.AddField(
            model_name='users',
            name='status',
            field=models.CharField(default='active', max_length=10),
        ),
    ]
